error: Add extended error transfer format
Extended error transfer format (through IPROTO_ERROR) has been added.

Extended error transfer format (through IPROTO_ERROR) has been added.
Which error transmission format (default or extended)
will be used depends on the session negotiation parameters.

@TarantoolBot document
Title: error: extended error transfer format
The error_extended option has been added to connection options.
This option adds a negotiation phase to the connection establishing.
It tries to establish a connection with the possibility of
transmitting errors in an extended format and throws an error
in case of failure.
The extended format also transmit a backtrace and custom type.

The new IPROTO_ERROR representation (using an array(MP_ARRAY)
is useful for the stacked diagnostics task)

0      5
+------++================+================++===================+
|      ||                |                ||                   |
| BODY ||   0x00: 0x8XXX |   0x01: SYNC   ||   0x31: ERROR     |
|HEADER|| MP_INT: MP_INT | MP_INT: MP_INT || MP_INT: MP_ARRAY  |
| SIZE ||                |                ||                   |
+------++================+================++===================+
 MP_INT                MP_MAP                      MP_MAP

Every error is a map with keys like ERROR_MSG, ERROR_BT ...

Example:
local connection = netbox.connect(host, port, {error_extended = true})

Needed for #4398