error: Add the custom error type
A possibility to create an error with a custom subtype was added.

In accordance with https://github.com/tarantool/tarantool/issues/4398
a custom error type has been added to the box.error.
Now, it's possible to create an error with a custom subtype (string value)
for use it in applications.

@TarantoolBot document
Title: error.custom_type
A custom error type has been added to the box.error.
Now, it's possible to create an error with a custom subtype (string value)
for use it in applications.

Example:

err_custom = box.error.new(box.error.CUSTOM_ERROR, "My Custom Type", "Reason")
Now:
err_custom.type == "CustomError"
err_custom.custom_type == "My Custom Type"
err_custom.message == "User custom error: Reason"

Needed for #4398