error: Add a Lua backtrace to error
Lua bactrace was added to a tarantool error.

In accordance with https://github.com/tarantool/tarantool/issues/4398
we want to have a Lua backtrace for the box.error

@TarantoolBot document
Title: error.bt

Lua backtrace was added to a tarantool error.

Needed for #4398