error: Add the custom error type
In accordance with https://github.com/tarantool/tarantool/issues/4398
a custom error type has been added to the box.error.
Now, it's possible to create an error with custom subtype (string value)
for use it in applications.

Needed for #4398